language: bash

env:
  global:
  - secure: JKtDA6aWY2DOfcalMm0Z/+Db6qn1bT0cIhUsqy8yQgIJh92HONFTcTBVOvvG1Vk95MqjTN+07ORU3OJU8/l2/t6oFi5wOKGtpxkvx0kVA+CE2HT0cFxF/Yqk3GYWLf1qV3pvw+/Hai4BF19OQLhc8vUS80rKm9Ld4LKPPXDJskAKQOqpcMoNVnvlo1WlZiKND25461h0IXxsdW7mt6ZCtW8Gk9vLJV+/CLBbAiybWNO4xfwzf6cQyGQieZW/eXO1aw7beimL9avELikfuVyynVFVXMAEi79QnFNtikyIOdWZlT8bPxG0NPkiYKSt79ZzrI93BzQJa7WnhcA2V5DflRzmtz00h8srR0msmytwBMaQo65PaApMYqCfyfKTQMzahyuYVpy/nqY5f9rm3TQfe3oN1JUGdRrRxKWf/ksGw7Qq9lh6gVNwfBQlBggMvnln6UeqGve5ef5hYSV9IhC5nlBWEvlNr8z3pGVqACqg3amz8COBtciYGDv1gdHbFkxWI8tQfbkYtNk+ZRm+Gq6rjjNinSZA6qUeHHXrO8rtiFUcX5XgR8T2KzHMa0MQtpveE9sJXP/LNgWFgiHy8xyWHQ64hw4If9tytJbHfYsx8hUW2QfYUKwHh8jmKuyKZhmvgQgKzXf/6e0AB+5nql8kLn8rU0P4tGrZ6C944NELii0=
  - secure: DiVPl+QZGAPk26RxDXksKADsxGaeV9znPyvrfCheXHgSlZUxMj+ZBaPom77dde6sHi+cv5je/+Y6gQRd8eZE6fdhj9aMs6Za6tcWXJkMJR3kgH9tapr9jJCLR4xaeZ/JK7snPBScwUZc1LYn2WGr7jm6yfWjhXqo97bTbwUSK/XCD1QyrPszxsEZ1Zwax6jpS4T6w7AuK91wfDjSO/mBq8UnWL3C0LKRZuwHr3wd4BTfSESIgPIScvomWt6810iJTLe477/CqjQtX9x/fYXXAeJDDBh+VOWGV66cv0q1avrmPNdZGCjHWNC9EZKft0BA7nTithCfEjUGDJjH1cZfIkc9BOGa41+UyYv5ebVeSYR9AQBnERWoQQval5UCySW6vJhn8q/9X1hI7IHNBY3MQNSYBE/xXQ6RPUL+mw19axvPgmpU6VGykMLYgz6DVO84C6C/vM26Ubv5axbUu03LCdeZDmqdA63z6TioOvgSxst5utXRZlQC0gEfYDoojU7SCyyrkpF1+mxFXPA0ilsuIhlT25pIXW+SB58PaHhdp5LcYnKV66HD3zhoIa80N6Kvw1jQOl6MTOeEabHBqjTAQffX8LBZ37LRkJLukJZ/73iPO100TWiBT3n1JxXSt21j9F6ZYH19F0ugwPgAEHHVsxq4qSRk6K4ZgEEdw5HycPo=

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build -t  abcbank/apiv1:latest    apiv1
  - docker image build -t  abcbank/web:latest      web
  - docker image build -t  abcbank/custinfo:latest custinfo
  - docker image push abcbank/apiv1:latest
  - docker image push abcbank/web:latest
  - docker image push abcbank/custinfo:latest

script:
  - tests/mytest.sh
