apiVersion: v1
kind: Pod
metadata:
  name: custinfo
  labels:
    app: custinfo
    appid: 7A252155
spec:
  hostname: custinfo
  containers:
    - image: abcbank/custinfo:latest
      name: custinfo
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
    appid: 89DBDBE0
spec:
  containers:
    - image: abcbank/web:latest
      name: web
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: apiv1
  labels:
    app: apiv1
    appid: 27AD61BD
spec:
  containers:
    - image: abcbank/apiv1:latest
      name: web
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
  selector:
    appid: 89DBDBE0
---
apiVersion: v1
kind: Service
metadata:
  name: apiv1
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30880
  selector:
    appid: 27AD61BD
---
apiVersion: v1
kind: Service
metadata:
  name: custinfo
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    appid: 7A252155
    